import React, { useEffect, useRef, useState } from 'react';
import { GraduationCap, LayoutDashboard, CalendarDays, BookOpen, ClipboardList, Clock3, Bell, Settings, ChevronLeft, ChevronRight, ChevronDown, Search, Plus, ArrowUpRight, MapPin, Users, Check, X, Download, List, Calendar, Menu, HelpCircle, Send, CheckCircle2, Sparkles } from 'lucide-react';
import { courses, sessions, dayNames, weekDates, shortDate, fullDate, time } from './data';

const nav = [ ['overview', 'Tổng quan', LayoutDashboard], ['schedule', 'Lịch giảng dạy', CalendarDays], ['courses', 'Lớp học phần', BookOpen], ['requests', 'Yêu cầu của tôi', ClipboardList], ['availability', 'Thời gian khả dụng', Clock3] ];
const titles = { overview: 'Tổng quan', schedule: 'Lịch giảng dạy', courses: 'Lớp học phần', requests: 'Yêu cầu của tôi', availability: 'Thời gian khả dụng', notifications: 'Thông báo', settings: 'Cài đặt', help: 'Trung tâm hỗ trợ' };
function readStorage(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }

function Modal({ title, children, onClose }) {
  const ref = useRef(null);
  useEffect(() => { const previous = document.activeElement; const dialog = ref.current; dialog.showModal(); const handler = e => { if (e.target === dialog) onClose(); }; dialog.addEventListener('click', handler); return () => { dialog.removeEventListener('click', handler); dialog.close(); previous?.focus(); }; }, []);
  return <dialog ref={ref} className="modal" onCancel={onClose}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Đóng"><X size={20}/></button></div>{children}</dialog>;
}

export default function App() {
  const [page, setPage] = useState('schedule');
  const [week, setWeek] = useState(0);
  const [view, setView] = useState('week');
  const [query, setQuery] = useState('');
  const [courseFilter, setCourseFilter] = useState('all');
  const [typeFilter, setTypeFilter] = useState('all');
  const [selected, setSelected] = useState(null);
  const [requestOpen, setRequestOpen] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [toast, setToast] = useState('');
  const [requests, setRequests] = useState(() => readStorage('campus-requests', []));
  const [availability, setAvailability] = useState(() => readStorage('campus-availability', []));
  const [read, setRead] = useState(() => readStorage('campus-read', false));
  const [profile, setProfile] = useState(() => readStorage('campus-profile', { name: 'Nguyễn Minh Anh', email: 'minhanh@ptit.edu.vn' }));
  const [storageError, setStorageError] = useState(false);
  const dates = weekDates(week);
  const visible = sessions.filter(s => (courseFilter === 'all' || String(s.course) === courseFilter) && (typeFilter === 'all' || s.type === typeFilter) && `${courses[s.course].name} ${courses[s.course].id} ${courses[s.course].room}`.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi')));
  useEffect(() => { try { localStorage.setItem('campus-requests', JSON.stringify(requests)); localStorage.setItem('campus-availability', JSON.stringify(availability)); localStorage.setItem('campus-read', JSON.stringify(read)); localStorage.setItem('campus-profile', JSON.stringify(profile)); } catch { setStorageError(true); } }, [requests, availability, read, profile]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4000); return () => clearTimeout(timer); }, [toast]);
  function navigate(next) { setPage(next); setQuery(''); setMobileOpen(false); }
  function exportCalendar() {
    const content = ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//Campus//Teaching Schedule//VI', ...visible.flatMap(s => { const date = fullDate(dates[s.day]).replaceAll('-', ''); const c = courses[s.course]; return ['BEGIN:VEVENT', `UID:campus-${s.id}-${date}@demo.local`, 'DTSTAMP:20261009T000000Z', `DTSTART:${date}T${String(s.start).padStart(2, '0')}0000`, `DTEND:${date}T${String(s.end).padStart(2, '0')}0000`, `SUMMARY:${c.name}`, `LOCATION:${c.room}`, 'END:VEVENT']; }), 'END:VCALENDAR'].join('\r\n');
    const url = URL.createObjectURL(new Blob([content], { type: 'text/calendar;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = `lich-giang-day-tuan-${9 + week}.ics`; a.click(); URL.revokeObjectURL(url); setToast('Đã xuất lịch tuần dưới dạng .ics');
  }
  function submitRequest(e) {
    e.preventDefault(); const data = Object.fromEntries(new FormData(e.target)); const session = sessions.find(s => String(s.id) === data.session);
    setRequests(prev => [{ ...data, id: Date.now(), course: courses[session.course].name, originalDate: fullDate(dates[session.day]), status: 'Chờ duyệt' }, ...prev]); setRequestOpen(false); setSelected(null); setToast('Đã lưu yêu cầu mẫu. Lịch chính thức chưa thay đổi.');
  }
  const nextSessions = sessions.filter(s => s.day === 4).sort((a, b) => a.start - b.start);
  return <div className="app-shell">
    {mobileOpen && <button className="sidebar-backdrop" aria-label="Đóng điều hướng" onClick={() => setMobileOpen(false)}/>}
    <aside className={`sidebar ${mobileOpen ? 'open' : ''}`}>
      <a className="brand" href="#" onClick={e => { e.preventDefault(); navigate('schedule'); }}><span className="brand-mark"><GraduationCap size={25}/></span><span>campus<span className="brand-dot">.</span><small>TEACHING WORKSPACE</small></span></a>
      <div className="workspace"><span className="school-icon"><GraduationCap size={19}/></span><div><strong>Học viện PTIT</strong><small>Cơ sở Hà Nội</small></div><span className="workspace-check"><Check size={13}/></span></div>
      <span className="nav-label">KHÔNG GIAN LÀM VIỆC</span>
      <nav>{nav.map(([id, label, Icon]) => <button key={id} onClick={() => navigate(id)} className={`nav-item ${page === id ? 'active' : ''}`}><Icon size={20}/><span>{label}</span>{id === 'requests' && requests.length > 0 && <b className="nav-count">{requests.length}</b>}{id === 'schedule' && <span className="active-dot"/>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="semester-card"><span className="semester-icon"><CalendarDays size={19}/></span><strong>Một học kỳ, thật chủ động.</strong><p>Sắp xếp thời gian. Tập trung vào những bài giảng tốt hơn.</p><span>Học kỳ I · 2026 – 2027 <ArrowUpRight size={15}/></span></div><button className={`nav-item ${page === 'settings' ? 'active' : ''}`} onClick={() => navigate('settings')}><Settings size={19}/>Cài đặt</button><button className="nav-item" onClick={() => navigate('help')}><HelpCircle size={19}/>Trợ giúp & hỗ trợ</button><div className="sidebar-user"><span className="avatar">MA</span><div><strong>{profile.name}</strong><small>Giảng viên cơ hữu</small></div><button className="icon-button" aria-label="Cài đặt tài khoản" onClick={() => navigate('settings')}><ChevronDown size={17}/></button></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Mở điều hướng" onClick={() => setMobileOpen(true)}><Menu size={22}/></button><span>Không gian giảng viên</span><ChevronRight size={14}/><strong>{titles[page]}</strong></div><div className="topbar-actions"><span className="today-label">Thứ Sáu, 09 tháng 10, 2026</span><button className="notification-button icon-button" aria-label="Xem thông báo" onClick={() => navigate('notifications')}><Bell size={20}/>{!read && <i/>}</button><button className="avatar avatar-small" aria-label="Tài khoản" onClick={() => navigate('settings')}>MA</button></div></header>
    <main><div className="page-heading"><div><div className="eyebrow"><span/> HỌC KỲ I · NĂM HỌC 2026 – 2027</div><h1>{titles[page]}<span className="heading-dot">.</span></h1><p>{page === 'schedule' ? 'Mỗi bài giảng đều có một kế hoạch tốt. Cùng xem tuần của bạn.' : 'Không gian của bạn, để mỗi ngày giảng dạy trở nên nhẹ nhàng hơn.'}</p></div><button className="button primary" onClick={() => { setSelected(null); setRequestOpen(true); }}><Plus size={18}/>Tạo yêu cầu</button></div>
    {storageError && <div role="alert" className="info-banner">Trình duyệt không cho phép lưu dữ liệu. Các thay đổi chỉ giữ trong phiên hiện tại.</div>}
    {(page === 'schedule' || page === 'overview') && <><div className="stats-grid"><Stat icon={CalendarDays} color="green" label="Buổi dạy trong tuần" value="07" note="Trên 5 ngày giảng dạy"/><Stat icon={Clock3} color="blue" label="Tổng giờ giảng" value="14" suffix="giờ" note="Kế hoạch tuần hiện tại"/><Stat icon={BookOpen} color="purple" label="Lớp học phần" value="04" note="155 sinh viên đang theo học"/><Stat icon={ClipboardList} color="orange" label="Yêu cầu chờ duyệt" value={String(requests.length).padStart(2, '0')} note="Theo dõi tại Yêu cầu của tôi"/></div>
    <div className="content-grid"><section className="calendar-panel"><div className="calendar-toolbar"><div><h2>{view === 'week' ? 'Lịch tuần' : 'Danh sách buổi dạy'} <span className="badge muted">Tuần {9 + week}</span></h2><p>{shortDate(dates[0])} – {shortDate(dates[6])}/{dates[6].getFullYear()}</p></div><div className="calendar-controls"><button className="button compact" onClick={() => setWeek(0)}>Hôm nay</button><div className="arrow-group"><button aria-label="Tuần trước" disabled={week <= -8} onClick={() => setWeek(w => w - 1)}><ChevronLeft size={18}/></button><button aria-label="Tuần sau" disabled={week >= 10} onClick={() => setWeek(w => w + 1)}><ChevronRight size={18}/></button></div><div className="view-switch"><button aria-label="Lịch tuần" aria-pressed={view === 'week'} className={view === 'week' ? 'selected' : ''} onClick={() => setView('week')}><Calendar size={17}/></button><button aria-label="Danh sách" aria-pressed={view === 'list'} className={view === 'list' ? 'selected' : ''} onClick={() => setView('list')}><List size={18}/></button></div></div></div>
    <div className="filter-bar"><label className="search-field"><Search size={17}/><input aria-label="Tìm môn học hoặc phòng" placeholder="Tìm môn học, mã lớp, phòng…" value={query} onChange={e => setQuery(e.target.value)}/></label><select aria-label="Lọc lớp học phần" value={courseFilter} onChange={e => setCourseFilter(e.target.value)}><option value="all">Tất cả lớp học</option>{courses.map((c, i) => <option key={c.id} value={i}>{c.name}</option>)}</select><button className="icon-button export-button" title="Xuất lịch .ics" aria-label="Xuất lịch .ics" onClick={exportCalendar}><Download size={18}/></button></div>
    {view === 'week' ? <div className="calendar-scroll"><div className="week-calendar"><div className="day-header"><div className="timezone">GMT+7</div>{dates.map((d, i) => <div key={i} className={`day ${fullDate(d) === '2026-10-09' ? 'current' : ''} ${i > 4 ? 'weekend' : ''}`}><span>{dayNames[i]}</span><b>{String(d.getDate()).padStart(2, '0')}</b>{fullDate(d) === '2026-10-09' && <i/>}</div>)}</div><div className="calendar-body"><div className="time-axis">{Array.from({ length: 11 }, (_, i) => <span key={i} style={{ top: i * 66 }}>{time(i + 7)}</span>)}</div>{dates.map((date, day) => <div key={day} className={`day-column ${day > 4 ? 'weekend' : ''} ${fullDate(date) === '2026-10-09' ? 'today-column' : ''}`}>{visible.filter(s => s.day === day).map(s => <button key={s.id} className={`session-card ${courses[s.course].color}`} style={{ top: (s.start - 7) * 66 + 5, height: (s.end - s.start) * 66 - 10 }} onClick={() => setSelected(s)}><span className="session-time">{time(s.start)} – {time(s.end)}{s.type === 'makeup' && <span className="makeup-dot" title="Dạy bù"/>}</span><strong>{courses[s.course].name}</strong><span className="session-code">{courses[s.course].id} · Nhóm {courses[s.course].group}</span><span className="session-room"><MapPin size={12}/>{courses[s.course].room}</span>{s.type === 'makeup' && <span className="makeup-label">Dạy bù</span>}</button>)}</div>)}</div></div></div> : <div className="session-list">{visible.length === 0 && <Empty text="Không có buổi dạy phù hợp với bộ lọc."/>}{visible.map(s => <button key={s.id} className="session-row" onClick={() => setSelected(s)}><span className={`course-square ${courses[s.course].color}`}><BookOpen size={20}/></span><div><strong>{courses[s.course].name}</strong><small>{dayNames[s.day]}, {shortDate(dates[s.day])} · {time(s.start)} – {time(s.end)}</small></div><span className="row-room">{courses[s.course].room}</span><ChevronRight size={18}/></button>)}</div>}
    <div className="calendar-footer"><div className="legend"><button onClick={() => setTypeFilter(typeFilter === 'regular' ? 'all' : 'regular')} aria-pressed={typeFilter === 'regular'}><i className="green-dot"/>Lịch chính thức</button><button onClick={() => setTypeFilter(typeFilter === 'makeup' ? 'all' : 'makeup')} aria-pressed={typeFilter === 'makeup'}><i className="purple-dot"/>Dạy bù</button></div><span><CheckCircle2 size={14}/> Lịch mẫu đã công bố</span></div></section>
    <aside className="right-rail"><section className="today-card"><div className="rail-title"><h2>Hôm nay</h2><span className="badge green-badge">09/10</span></div><p className="rail-subtitle">Một ngày để truyền cảm hứng.</p>{nextSessions.map((s, i) => <button className="today-session" key={s.id} onClick={() => { setWeek(0); setSelected(s); }}><div className="today-time"><i className={courses[s.course].color}/>{time(s.start)} – {time(s.end)}<span>{i === 0 ? 'Buổi sáng' : 'Buổi chiều'}</span></div><strong>{courses[s.course].name}</strong><small><MapPin size={13}/>Phòng {courses[s.course].room}</small><small><Users size={13}/>{courses[s.course].students} sinh viên · Nhóm {courses[s.course].group}</small><span className="today-detail">Chi tiết buổi dạy <ArrowUpRight size={14}/></span></button>)}</section>
    <section className="notice-card"><div className="rail-title"><h2>Thông báo mới</h2><span className="notification-count">2</span></div><button className="notice-item" onClick={() => navigate('notifications')}><span className="notice-icon"><CalendarDays size={17}/></span><div><strong>Lịch tuần 9 đã được công bố</strong><p>Lịch giảng dạy từ 05/10 đến 11/10 đã sẵn sàng.</p><small>08/10/2026 · Phòng đào tạo</small></div></button><button className="notice-item" onClick={() => navigate('notifications')}><span className="notice-icon purple"><CheckCircle2 size={17}/></span><div><strong>Lịch dạy bù được xác nhận</strong><p>Quản lý dự án phần mềm · Thứ Năm, 13:00.</p><small>07/10/2026 · Phòng đào tạo</small></div></button><button className="text-link" onClick={() => navigate('notifications')}>Xem tất cả thông báo <ChevronRight size={15}/></button></section>
    <section className="tip-card"><Sparkles size={21}/><h3>Chủ động hơn mỗi tuần</h3><p>Cần điều chỉnh lịch? Gửi yêu cầu để phòng đào tạo hỗ trợ bạn kịp thời.</p><button onClick={() => setRequestOpen(true)}>Tạo yêu cầu mới <ArrowUpRight size={16}/></button><div className="tip-decoration"/></section></aside></div></>}
    {page === 'courses' && <div className="course-grid">{courses.map(c => <section className="course-panel" key={c.id}><span className={`course-square ${c.color}`}><BookOpen size={23}/></span><span className="badge green-badge">Đang giảng dạy</span><h2>{c.name}</h2><p>{c.id} · Nhóm {c.group}</p><div><span><Users size={16}/>{c.students} sinh viên</span><span><MapPin size={16}/>{c.room}</span></div><button className="text-link" onClick={() => { setCourseFilter(String(courses.indexOf(c))); navigate('schedule'); }}>Xem lịch lớp học <ArrowUpRight size={16}/></button></section>)}</div>}
    {page === 'requests' && <section className="standalone-panel"><div className="panel-title"><h2>Lịch sử yêu cầu <span className="badge muted">{requests.length}</span></h2><span className="muted-text">Yêu cầu được lưu trên trình duyệt</span></div>{requests.length === 0 ? <Empty text="Bạn chưa có yêu cầu nào. Tạo yêu cầu nghỉ hoặc đề xuất dạy bù từ một buổi dạy."/> : requests.map(r => <article className="request-row" key={r.id}><span className="notice-icon"><ClipboardList size={20}/></span><div><strong>{r.type} · {r.course}</strong><p>Buổi gốc: {r.originalDate} · {r.reason}</p>{r.date && <small>Đề xuất: {r.date} · {r.start} – {r.end}</small>}</div><span className="badge orange-badge">{r.status}</span></article>)}<div className="info-banner">Ở bản frontend mẫu, yêu cầu chờ duyệt không làm thay đổi lịch giảng dạy.</div></section>}
    {page === 'availability' && <section className="standalone-panel"><h2>Khai báo thời gian có thể giảng dạy</h2><p className="muted-text">Chọn khung thời gian để điều phối viên tham khảo khi lập lịch.</p><form className="availability-form" onSubmit={e => { e.preventDefault(); const d = Object.fromEntries(new FormData(e.target)); if (d.end <= d.start) { setToast('Giờ kết thúc phải sau giờ bắt đầu.'); return; } setAvailability(prev => [...prev, { ...d, id: Date.now() }]); e.target.reset(); setToast('Đã lưu khung thời gian mẫu.'); }}><label>Môn học<select name="course">{courses.map(c => <option key={c.id}>{c.name}</option>)}</select></label><label>Ngày<input required type="date" name="date" min="2026-08-10" max="2026-12-20"/></label><label>Từ<input required type="time" name="start"/></label><label>Đến<input required type="time" name="end"/></label><button className="button primary"><Plus size={17}/>Thêm khung giờ</button></form>{availability.length === 0 && <Empty text="Chưa có khung giờ khả dụng. Thêm khung giờ đầu tiên của bạn."/>}{availability.map(a => <div className="request-row" key={a.id}><Clock3 size={20}/><div><strong>{a.course}</strong><p>{a.date} · {a.start} – {a.end}</p></div><button className="icon-button" aria-label="Xóa khung giờ" onClick={() => setAvailability(prev => prev.filter(x => x.id !== a.id))}><X size={18}/></button></div>)}</section>}
    {page === 'notifications' && <section className="standalone-panel"><div className="panel-title"><h2>Hộp thông báo</h2><button className="button" onClick={() => { setRead(true); setToast('Đã đánh dấu tất cả là đã đọc.'); }}><Check size={16}/>Đánh dấu đã đọc</button></div><article className="request-row"><CalendarDays size={23}/><div><strong>Lịch tuần 9 đã được công bố</strong><p>Lịch giảng dạy từ 05/10/2026 đến 11/10/2026. Vui lòng kiểm tra thông tin buổi dạy và phòng học.</p><small>08/10/2026 · Phòng đào tạo</small></div></article><article className="request-row"><CheckCircle2 size={23}/><div><strong>Lịch dạy bù được xác nhận</strong><p>Quản lý dự án phần mềm · Nhóm 02 · 08/10/2026, 13:00 – 15:00 · Phòng 601-NT.</p><small>07/10/2026 · Phòng đào tạo</small></div></article></section>}
    {page === 'settings' && <section className="standalone-panel settings-panel"><h2>Thông tin cá nhân</h2><p className="muted-text">Cập nhật thông tin hiển thị trong bản mẫu.</p><form onSubmit={e => { e.preventDefault(); setProfile(Object.fromEntries(new FormData(e.target))); setToast('Đã lưu thông tin cá nhân.'); }}><label>Họ và tên<input name="name" defaultValue={profile.name} required maxLength={80}/></label><label>Email<input name="email" type="email" defaultValue={profile.email} required/></label><label>Vai trò<input value="Giảng viên cơ hữu" readOnly/></label><button className="button primary">Lưu thay đổi</button></form></section>}
    {page === 'help' && <section className="standalone-panel help-panel"><h2>Mọi thứ bạn cần cho một tuần chủ động</h2><details open><summary>Làm thế nào để xem lịch giảng dạy?</summary><p>Mở Lịch giảng dạy, dùng mũi tên để chuyển tuần. Chọn một thẻ môn học để xem phòng, lớp và giờ học. Bạn có thể lọc theo môn học hoặc xuất tệp lịch .ics.</p></details><details><summary>Tôi muốn xin nghỉ hoặc đề xuất dạy bù</summary><p>Chọn buổi dạy và bấm Gửi yêu cầu, nhập lý do và thời gian đề xuất. Yêu cầu cần được điều phối viên duyệt trước khi lịch chính thức thay đổi.</p></details><details><summary>Dữ liệu ở bản này được lưu ở đâu?</summary><p>Đây là frontend sử dụng lịch mẫu lặp theo tuần. Yêu cầu, thông tin cá nhân và thời gian khả dụng được lưu trên trình duyệt hiện tại. Backend chưa được tích hợp.</p></details></section>}
    <footer className="page-footer"><span>© 2026 Campus · Không gian giảng dạy của bạn</span><span><i/>Bản trải nghiệm · Dữ liệu mẫu</span></footer>
    </main></div>
    {selected && !requestOpen && <Modal title="Chi tiết buổi giảng" onClose={() => setSelected(null)}><div className={`detail-course ${courses[selected.course].color}`}><BookOpen size={25}/><h3>{courses[selected.course].name}</h3><p>{courses[selected.course].id} · Nhóm {courses[selected.course].group}</p></div><div className="detail-grid"><div><small>Ngày giảng dạy</small><strong>{dayNames[selected.day]}, {shortDate(dates[selected.day])}/{dates[selected.day].getFullYear()}</strong></div><div><small>Thời gian</small><strong>{time(selected.start)} – {time(selected.end)}</strong></div><div><small>Phòng học</small><strong>{courses[selected.course].room} · Cơ sở Ngọc Trục</strong></div><div><small>Sĩ số</small><strong>{courses[selected.course].students} sinh viên</strong></div><div><small>Trạng thái</small><strong>{selected.type === 'makeup' ? 'Dạy bù · Đã xác nhận' : 'Lịch chính thức'}</strong></div>{selected.type === 'makeup' && <div><small>Buổi gốc cần dạy bù</small><strong>Nhóm 02 · 28/09/2026, 09:00</strong></div>}</div><button className="button primary full-width" onClick={() => setRequestOpen(true)}><Send size={16}/>Gửi yêu cầu cho buổi dạy</button></Modal>}
    {requestOpen && <RequestModal selected={selected} dates={dates} onClose={() => setRequestOpen(false)} onSubmit={submitRequest}/>}
    {toast && <div className="toast" role="status"><CheckCircle2 size={19}/>{toast}<button aria-label="Đóng thông báo" onClick={() => setToast('')}><X size={16}/></button></div>}
  </div>;
}

function Stat({ icon: Icon, color, label, value, suffix, note }) { return <section className="stat-card"><div className="stat-top"><span>{label}</span><span className={`stat-icon ${color}`}><Icon size={19}/></span></div><div className="stat-value">{value}<small>{suffix}</small></div><p>{note}</p></section>; }
function Empty({ text }) { return <div className="empty-state"><CalendarDays size={36}/><p>{text}</p></div>; }
function RequestModal({ selected, dates, onClose, onSubmit }) {
  const [type, setType] = useState('Xin nghỉ'); const [error, setError] = useState('');
  return <Modal title="Tạo yêu cầu học vụ" onClose={onClose}><form className="request-form" onSubmit={e => { const d = Object.fromEntries(new FormData(e.target)); if (type === 'Đề xuất dạy bù' && d.end <= d.start) { e.preventDefault(); setError('Giờ kết thúc phải sau giờ bắt đầu.'); return; } onSubmit(e); }}><p className="muted-text">Gửi đề xuất để phòng đào tạo xem xét và điều chỉnh lịch.</p><label>Loại yêu cầu<select name="type" value={type} onChange={e => { setType(e.target.value); setError(''); }}><option>Xin nghỉ</option><option>Đề xuất dạy bù</option></select></label><label>Buổi dạy liên quan<select name="session" defaultValue={selected?.id ?? 1}>{sessions.map(s => <option key={s.id} value={s.id}>{courses[s.course].name} · {shortDate(dates[s.day])} · {time(s.start)}</option>)}</select></label>{type === 'Đề xuất dạy bù' && <><label>Ngày đề xuất<input type="date" name="date" required min="2026-10-09" max="2026-12-20"/></label><div className="form-two"><label>Từ<input name="start" type="time" required/></label><label>Đến<input name="end" type="time" required/></label></div></>}<label>Lý do<textarea name="reason" placeholder="Nhập lý do và thông tin cần thiết…" required minLength={5} maxLength={1000} rows={3}/></label>{error && <p role="alert" className="error-text">{error}</p>}<div className="info-banner">Yêu cầu mẫu được lưu trên trình duyệt và ở trạng thái chờ duyệt.</div><button className="button primary full-width" type="submit"><Send size={16}/>Gửi yêu cầu</button></form></Modal>;
}
